---
chat-format: '<{PREFIX} {USER_NAME}> {MESSAGE}'
custom-nametag: '<{PREFIX} {USER_NAME}>'
enable-op-override: true
message-on-insufficient-permissions: I don't think you have permission to do this...
message-on-insufficient-build-permission: You don't have permission to build here.
message-on-rank-change: Your rank has been changed into a / an {RANK}!
...