name: xPermsMgr
main: _64FF00\xPermsMgr\xPermsMgr
version: 1.6.0
api: [1.0.0]
load: STARTUP
author: 64FF00
description: Custom Permissions Plugin for PocketMine!
website: https://github.com/64FF00/xPermsMgr
commands:
 xpmgr:
  description: Provides access to xPermsMgr commands.
  usage: "/xpmgr <groups / reload / setrank / users>"
  permission: xpmgr.command
permissions:
 xpmgr:
  default: op
  description: "Allows you to use all the xPermsMgr things!"
  children:
   xpmgr.build:
    default: true
    description: "Allows you to break and place blocks!"
   xpmgr.command:
    default: op
    description: "Allows you to use all the xPermsMgr commands!"
    children:
     xpmgr.command.groups:
      default: op
      description: "Allows you to see the list of all groups!"
     xpmgr.command.reload:
      default: op
      description: "Allows you to reload the config files!"
     xpmgr.command.setperm:
      default: op
      description: "Allows you to set permissions for a user or a group!"
     xpmgr.command.setrank:
      default: op
      description: "Allows you to set group for a user!"
     xpmgr.command.users:
      default: op
      description: "Allows you to see the list of all users!"